### ISSUE TITLE
Profilside: gå til Edit Profile

### ISSUE THREAD

**Issue by iskold123** [iskold123/Idevent#10]
### Describe why you want this feature
Som bruger ønsker jeg at kunne ændre mine personlige oplysninger, Navn, adresse m.m.
 
### Describe the solution you'd like
Når man trykker på 'Edit' knappen føres man til Edit Profile siden. Her kan man ændre sine oplysninger, hvilket gemmes når man trykker Save.
 
### Additional context
Edit Profile bruges også når man redigere brugere som admin.

**Comment by Ronnie1983** [comment]
Duplicate
